# Generated by Django 5.2.7 on 2026-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerFilterOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=50, verbose_name='نوع الفلتر')),
                ('option_value', models.CharField(max_length=100, verbose_name='قيمة الفلتر')),
                ('display_name', models.CharField(max_length=100, verbose_name='الاسم المعروض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خيار فلتر المحامين',
                'verbose_name_plural': 'خيارات فلتر المحامين',
                'ordering': ['option_type', 'sort_order', 'display_name'],
                'unique_together': {('option_type', 'option_value')},
            },
        ),
    ]
