# Generated by Django 5.2.7 on 2026-04-13 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0004_add_archive_lifecycle_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='الموكل'),
        ),
        migrations.AlterField(
            model_name='lawsuit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الدعوى'),
        ),
    ]
