# Generated by Django 5.2.7 on 2026-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_legalprocedurenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='العنوان')),
                ('category', models.CharField(max_length=200, verbose_name='الفئة')),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط المصدر')),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط PDF')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مكتبة القوانين',
                'verbose_name_plural': 'مكتبة القوانين',
                'db_table': 'lawsuits_lawlibrary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الكلمة المفتاحية')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='الرابط النصي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كلمة مفتاحية',
                'verbose_name_plural': 'كلمات مفتاحية',
                'ordering': ['name'],
            },
        ),

        migrations.AddField(
            model_name='law',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط PDF'),
        ),
        migrations.AddField(
            model_name='law',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='الرابط النصي'),
        ),
        migrations.AddField(
            model_name='law',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط المصدر'),
        ),
        migrations.AddField(
            model_name='legalcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='الرابط النصي'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='laws_tag_name_751895_idx'),
        ),
        migrations.AddField(
            model_name='law',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='law_tags', related_name='laws', to='laws.tag', verbose_name='الكلمات المفتاحية'),
        ),
    ]
