# Generated by Django 5.2.7 on 2026-04-28 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatlog',
            options={'ordering': ['created_at'], 'verbose_name': 'سجل محادثة AI', 'verbose_name_plural': 'سجلات محادثات AI'},
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='محادثة جديدة', max_length=255, verbose_name='عنوان المحادثة')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشفة')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='مفضلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة ذكية',
                'verbose_name_plural': 'المحادثات الذكية',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='aichatlog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='logs.aiconversation', verbose_name='المحادثة'),
        ),
        migrations.AddIndex(
            model_name='aichatlog',
            index=models.Index(fields=['conversation'], name='logs_aichat_convers_ceb53a_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user'], name='logs_aiconv_user_id_585d01_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['updated_at'], name='logs_aiconv_updated_235965_idx'),
        ),
    ]
