# Generated by Django 5.2.7 on 2026-05-05 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="المسار أو المعرف الفريد للخدمة (مثل: /lawsuits, /chat, /inheritance)",
                        max_length=100,
                        unique=True,
                        verbose_name="مفتاح الخدمة",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الخدمة (عربي)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الخدمة (إنجليزي)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الخدمة"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="settings",
                        help_text="اسم أيقونة Material Icons",
                        max_length=100,
                        verbose_name="أيقونة",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legal", "قانوني"),
                            ("financial", "مالي"),
                            ("ai", "ذكاء اصطناعي"),
                            ("admin", "إداري"),
                            ("general", "عام"),
                            ("communication", "تواصل"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="مفعّلة"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="مميزة (Premium)"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "خدمة",
                "verbose_name_plural": "الخدمات",
                "ordering": ["sort_order", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="RoleServicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("judge", "قاضي"),
                            ("lawyer", "محامي"),
                            ("assistant", "معاون محامي"),
                            ("notary", "كاتب عدل"),
                            ("citizen", "مواطن"),
                            ("admin", "مدير"),
                        ],
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="مفعّلة لهذا الدور"),
                ),
                (
                    "max_daily_uses",
                    models.IntegerField(
                        default=0,
                        help_text="0 = بلا حدود",
                        verbose_name="حد الاستخدام اليومي",
                    ),
                ),
                (
                    "max_monthly_uses",
                    models.IntegerField(
                        default=0,
                        help_text="0 = بلا حدود",
                        verbose_name="حد الاستخدام الشهري",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="control_panel.servicedefinition",
                        verbose_name="الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلاحية خدمة لدور",
                "verbose_name_plural": "صلاحيات الخدمات حسب الأدوار",
                "ordering": ["role", "service__sort_order"],
                "unique_together": {("role", "service")},
            },
        ),
        migrations.CreateModel(
            name="ServiceUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الوصول"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="مدة الاستخدام (ثواني)"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="control_panel.servicedefinition",
                        verbose_name="الخدمة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل استخدام خدمة",
                "verbose_name_plural": "سجلات استخدام الخدمات",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="serviceusagelog",
            index=models.Index(fields=["user", "service", "accessed_at"], name="control_pan_user_id_5c43c1_idx"),
        ),
        migrations.AddIndex(
            model_name="serviceusagelog",
            index=models.Index(fields=["service", "accessed_at"], name="control_pan_service__2a8ef8_idx"),
        ),
    ]
