# Generated by Django 5.2.7 on 2026-04-16 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
        ('lawsuits', '0006_casefileitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='archive_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الأرشفة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='archive_status',
            field=models.CharField(choices=[('active', 'نشط'), ('semi_active', 'شبه نشط'), ('archived', 'محفوظ')], default='active', max_length=20, verbose_name='حالة الأرشفة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_hearings', to=settings.AUTH_USER_MODEL, verbose_name='أرشف بواسطة'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['archive_status'], name='hearings_he_archive_7ba830_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['is_deleted'], name='hearings_he_is_dele_a61f76_idx'),
        ),
    ]
