# Generated by Django 5.2.7 on 2026-04-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('allowed_roles', models.CharField(help_text='ex: lawyer,notary', max_length=200, verbose_name='الأدوار المسموحة')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر الشهري')),
                ('max_ai_searches', models.IntegerField(default=10, verbose_name='أقصى عدد لاستعلامات الذكاء الاصطناعي')),
                ('max_library_searches', models.IntegerField(default=50, verbose_name='أقصى عدد للبحث في المكتبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الاشتراك')),
                ('ai_searches_used', models.IntegerField(default=0, verbose_name='استعلامات AI المستخدمة')),
                ('library_searches_used', models.IntegerField(default=0, verbose_name='بحوث المكتبة المستخدمة')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.package', verbose_name='الباقة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
