# Generated by Django 5.2.7 on 2026-04-13 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usersubscription_package_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_accounts', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول (المحامي)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('judge', 'قاضي'), ('lawyer', 'محامي'), ('assistant', 'معاون محامي'), ('notary', 'كاتب عدل'), ('citizen', 'مواطن'), ('admin', 'مدير')], default='citizen', max_length=20, verbose_name='الدور'),
        ),
    ]
