# Generated by Django 6.0.1 on 2026-02-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('lawsuits', '0003_financialclaim_legaltemplate_lawsuit_case_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='archive_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الأرشفة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='archive_status',
            field=models.CharField(choices=[('active', 'نشط'), ('semi_active', 'شبه نشط'), ('archived', 'محفوظ')], default='active', max_length=20, verbose_name='حالة الأرشفة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_lawsuits', to=settings.AUTH_USER_MODEL, verbose_name='أرشف بواسطة'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='parent_lawsuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_lawsuits', to='lawsuits.lawsuit', verbose_name='الدعوى الأصلية'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['archive_status'], name='lawsuits_la_archive_3ce910_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['is_deleted'], name='lawsuits_la_is_dele_e30f71_idx'),
        ),
        migrations.AddIndex(
            model_name='lawsuit',
            index=models.Index(fields=['parent_lawsuit'], name='lawsuits_la_parent__598f5b_idx'),
        ),
    ]
