# Generated by Django 6.0.4 on 2026-04-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0005_lawsuit_client_alter_lawsuit_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('document', 'مستند'), ('lawsuit', 'دعوى'), ('appeal', 'طعن'), ('payment_order', 'أمر أداء'), ('judgment', 'حكم'), ('hearing_record', 'محضر جلسة'), ('response', 'مذكرة / رد'), ('contract', 'عقد'), ('evidence', 'دليل'), ('other', 'أخرى')], default='document', max_length=30, verbose_name='نوع العنصر')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العنصر')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('file', models.FileField(blank=True, null=True, upload_to='case_files/lawsuit_id/', verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكيان المرتبط')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع الكيان المرتبط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_file_items', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('lawsuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_file_items', to='lawsuits.lawsuit', verbose_name='القضية')),
            ],
            options={
                'verbose_name': 'عنصر ملف القضية',
                'verbose_name_plural': 'عناصر ملف القضية',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['lawsuit'], name='lawsuits_ca_lawsuit_ffcecd_idx'), models.Index(fields=['item_type'], name='lawsuits_ca_item_ty_186a27_idx'), models.Index(fields=['related_object_id', 'related_object_type'], name='lawsuits_ca_related_435c3e_idx'), models.Index(fields=['created_at'], name='lawsuits_ca_created_b70774_idx')],
            },
        ),
    ]
