# Generated by Django 6.0.4 on 2026-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0006_casefileitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawsuit',
            name='case_subtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='النوع الفرعي'),
        ),
        migrations.AddField(
            model_name='lawsuit',
            name='case_year_hijri',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة القضية (هجري)'),
        ),
    ]
