# Generated by Django 6.0.4 on 2026-04-16 22:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('lawsuits', '0008_case_entity_and_link_lawsuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='subject',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='موضوع القضية'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='lawsuits_ca_case_nu_407be2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_status'], name='lawsuits_ca_case_st_dede2b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['governorate'], name='lawsuits_ca_governo_10a60e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='lawsuits_ca_created_700deb_idx'),
        ),
    ]
