# Generated by Django 5.2.7 on 2026-04-17 17:41

import smartju.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawsuits', '0010_case_type_subtype_and_caseparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefileitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='case_files/lawsuit_id/', validators=[smartju.validators.validate_file_size, smartju.validators.validate_file_extension], verbose_name='الملف'),
        ),
    ]
