# Generated by Django 5.2.7 on 2026-04-17 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hearing', 'جلسة'), ('lawsuit', 'دعوى'), ('judgment', 'حكم'), ('appeal', 'طعن'), ('payment', 'دفع'), ('message', 'رسالة'), ('system', 'نظام')], default='system', max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, default='', verbose_name='المحتوى')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكيان المرتبط')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع الكيان المرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
