# Generated by Django 6.0.4 on 2026-04-14 19:36

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='مضمون المستند'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='evidence_basis',
            field=models.TextField(blank=True, default='', verbose_name='وجه الاستدلال'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_upload_path, verbose_name='الملف المرفق'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='gregorian_date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ الميلادي'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='hijri_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='التاريخ الهجري'),
        ),
    ]
