# Generated by Django 5.2.7 on 2026-04-17 17:41

import attachments.models
import smartju.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.attachment_upload_path, validators=[smartju.validators.validate_file_size, smartju.validators.validate_file_extension], verbose_name='الملف المرفق'),
        ),
    ]
