# Generated by Django 5.2.7 on 2026-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('grade', models.CharField(max_length=50, verbose_name='الدرجة')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفرع')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('directorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المديرية')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('address_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل العنوان')),
                ('office_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المكتب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'محامي',
                'verbose_name_plural': 'المحامين',
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['name'], name='lawyers_law_name_50eeca_idx'), models.Index(fields=['governorate'], name='lawyers_law_governo_05afe8_idx'), models.Index(fields=['grade'], name='lawyers_law_grade_772636_idx')],
            },
        ),
    ]
