# Generated by Django 6.0.4 on 2026-04-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'استعراض'), ('other', 'أخرى')], default='other', max_length=32)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
            },
        ),
    ]
